### PR TITLE
fix spectators able to respawn

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
image

**Comment by J-VdS** [comment]
Nope they can spawn where they are at the moment

**Comment by j-vds** [comment]
Nope they can spawn where they are at the moment. Changing the spawn doesn't help too

**Comment by ghost** [comment]
why is that?

**Comment by ghost** [comment]
Looking at hexedplugin, losing core makes you not spawn.

**Comment by j-vds** [comment]
I made some changes and send the jar to Somka
I am using the `player.kill()` method now (just as Anuke did)
But I cannot fully test it bc I only have 2 devices...

**Comment by ghost** [comment]
👍

**Pull request closed without merging**
